# Generated by Django 5.2.5 on 2025-09-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_about_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='skills_heading',
            field=models.CharField(default='My Skills', max_length=200),
        ),
    ]
